set(CTEST_PROJECT_NAME "rtimdb")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "192.168.200.81")
set(CTEST_DROP_LOCATION "/submit.php?project=rtimdb")
set(CTEST_DROP_SITE_CDASH TRUE)
